services:
  sveta_landing_page:
    build:
      context: ./src/sveta.landing-page
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
    image: ${DOCKER_HUB_USERNAME:-sveta}/sveta_landing_page:${PLATFORM:-linux}-${TAG:-latest}
    profiles:
      - landing_page
    networks:
      - sveta_network

  sveta_api:
    image: ${DOCKER_HUB_USERNAME:-sveta}/sveta_api:${PLATFORM:-linux}-${TAG:-latest}
    profiles:
      - backend
    build:
      context: ./src
      dockerfile: sveta.backend/src/Api/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - Sk:ApiKey=$API_SK_API_KEY
      - Sk:Uri=$API_SK_URI
      - Sk:EmbeddingUri=$API_SK_EMBEDDING_URI
      - Sk:StoreUri=$API_SK_STORE_URI
      - Postgres:ConnexionString=$API_DATABASE_CONNEXION_STRING
    ports:
      - "8080:8080"
    networks:
      - sveta_network
    depends_on:
      - redis
      - embedding_service
  
  redis:
    image: redis/redis-stack:latest
    profiles:
      - backend
    ports:
      - "6379:6379"
      - "8002:8001"
    volumes:
      - redis-data:/data
    networks:
      - sveta_network
  
  embedding_service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.6
    environment:
      - MODEL_ID=intfloat/multilingual-e5-large-instruct
    ports:
      - "8081:80"
    volumes:
      - embedding_data:/data
    networks:
      - sveta_network
    profiles:
      - backend
  
  sveta_database:
    image: postgres
    profiles:
      - backend
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5433:5432"
    volumes:
      - sveta_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - sveta_network


volumes:
  redis-data:
  embedding_data:
  sveta_data:

networks:
  sveta_network:
    external: true
