name: Deploy to Server

on:
  workflow_dispatch:

env:
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Check Files at Root
        run: ls -la

      - name: Prepare Files for Deployment
        run: |
          mkdir -p deploy
          cp docker-compose.yml Makefile deploy/

      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "deploy/*"
          target: "~/sveta/"
          debug: true
          strip_components: 1

      - name: Run Make Prod on Server with Environment Variables
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
        script: |
          cd ~/sveta
          echo "Création du fichier .env avec toutes les variables d'environnement..."
          printenv | grep '^ENV_' | sed 's/^ENV_//' > .env
          echo "Contenu du fichier .env généré :"
          cat .env
          make deploy-prod
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
